Add color to the Character commands
lukevp/ESC-POS-.NET pull request #93
Opened 2020-12-02 11:17 UTC by lewisvive

Added ability to set print color.

2021-02-15 01:09 UTC, lukevp requested changes
Thanks for the PR! minor change on suppressions and there's a conflict that must be resolved before merge.

2021-02-15 01:09 UTC, lukevp commented on ESCPOS_NET/Emitters/Enums/Color.cs
> +    [System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1025:Code should not contain multiple whitespace in a row", Justification = "Enums are easier to read if they h
I agree with the justification, but the enum below doesn't have whitespace alignment. Can you move this to the suppressions file instead?

2021-08-13 21:21 UTC, FedericoBernardi commented
Any plan to merge it in master?

2021-08-29 23:53 UTC, lukevp approved these changes

2021-08-29 23:54 UTC, lukevp commented
Hi @FedericoBernardi  I was waiting for resolution of this comment: 
![image](https://user-images.githubusercontent.com/1251016/131269476-44bfcc2c-662e-4319-8bc5-02a2d467dea4.png)

However, sinc eyou asked for this I will go ahead and merge and resolve this so we can move forward with this functionality and I'll make the changes directly.

2021-08-29 23:54 UTC, merged